plugins {
    id 'java'
    id 'application'
}

group = 'com.sach'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral() // noi Gradle tim va tai thu vien ve
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'com.sach.vidu.App'
}

test {
    useJUnitPlatform()
}
